### ISSUE TITLE
Discussão da História

### ISSUE THREAD

**Issue by eduardodinizf** [LotusAttic/fairytail-bilbo#2]
Issue destinado a proposição e discussão de ideias base para o RPG da gente. Acho legal a gente tentar ser bem direto e sucinto na discussão pra não ficar longa demais(parecendo um chat de whatsapp).

**-Minha ideia:**

É um futuro distópico, a atmosfera terrestre não tem mais condições de suportar a vida humana, apenas alguns animais conseguiram se adaptar e viver em microrregiões pela crosta, o nível dos oceanos se elevaram centenas de metros devido a derretimento nos pólos e afundamento de placas tectônicas. A humanidade não conseguiu colonizar outros planetas e se viu forçada a entrar na crosta ou ir pros oceanos, se fracionando e se reorganizando em novas unidades políticas e territoriais. Obviamente, grande parte da população foi dizimada e apenas as classes mais altas e ricas tiveram condições de se reestabelecer, os poucos que foram aceitos para compor os novos "feudos" tiveram de se sujeitar a trabalhos degradantes e altamente insalubres, a dignidade humana era algo praticamente esquecido.

O conhecimento comum diz que ir à crosta ainda é possível, porém com muitos riscos: A permanência nela é impraticável devido às ocorrências climáticas severas, nível de oxigênio extremamente baixo, níveis de radiação ultravioleta e amplitude térmica gigantesca. Apenas poucas máquinas não tripuladas têm autorização e acesso à crosta.

**Nesse cenário, o jogo propõe que você escolha se será um habitante:**

1-_Das Profundezas Molhadas_
2-_Dos Labirintos Rochosos_
3-_Das Torres Metálicas_

A depender da escolha, o jogador terá diferentes itens iniciais e parâmetros para o jogo(ex.: agilidade, força, etc.).

O jogo começa em meio a uma rebelião causada por rumores de que um novo estado ainda mais elitista estava a se estabelecer na troposfera e que a atmosfera estava praticamente reestabelecida, porém esse novo estado era restrito a pessoas das cúpulas -ou nobrezas- desses 3 estados. A ideia que os rebelados têm é que os líderes estão a criar uma casta, fazendo com que apenas a nobreza ocupe a face da Terra.

**O objetivo do jogador é evitar ser pego pelos guardas da nobreza(humanos e robôs), passar por labirintos, coletar recursos para abrir portas, lutar, se curar e conseguir chegar à crosta.**

**Comment by Brunaicastro** [comment]
Ficou muito boa sua ideia!! Aprovado!!
